// <auto-generated />
namespace OnlineRealEstate.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202008211323521_d-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
